import type { Metadata } from "next";
import { heebo } from "../../utils/fonts";
import "./globals.css";

import NavBar from "../../components/NavBar";

import { AuthProvider } from "../../context/AuthContext";

export const metadata: Metadata = {
  title: "recipes web app",
  description: "Generated by ❤️",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <AuthProvider>
      <html lang="he" dir="rtl">
        <body className={`${heebo} font-heebo h-dvh`}>
          <NavBar />
          {children}
        </body>
      </html>
    </AuthProvider>
  );
}
